name: Build and Push Docker Image to GHCR

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (default: latest)'
        required: false
        default: 'latest'
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'context/**'
      - '.github/workflows/docker-release.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get ACL2 commit hash
        id: acl2-commit
        run: |
          ACL2_COMMIT=$(curl --silent https://api.github.com/repos/acl2/acl2/commits/master | jq -r .sha)
          echo "commit=$ACL2_COMMIT" >> $GITHUB_OUTPUT
          echo "ACL2 commit: $ACL2_COMMIT"

      - name: Determine image tag
        id: meta
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            TAG="${{ github.event.release.tag_name }}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TAG="${{ github.event.inputs.tag }}"
          else
            TAG="latest"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "Image tag: $TAG"

      - name: Extract metadata for Docker
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.meta.outputs.tag }}
            type=raw,value=latest,enable=${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
            type=semver,pattern={{version}},enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{major}}.{{minor}},enable=${{ github.event_name == 'release' }}
            type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v5
        continue-on-error: true
        with:
          context: context
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=quay.io/jupyter/minimal-notebook:latest
            ACL2_COMMIT=${{ steps.acl2-commit.outputs.commit }}
            ACL2_CERTIFY_OPTS=-j 6
            ACL2_CERTIFY_TARGETS=basic
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false

      - name: Extract make.log on build failure
        if: steps.docker-build.outcome == 'failure'
        continue-on-error: true
        run: |
          echo "Build failed, attempting to extract make.log..."
          mkdir -p ./build-logs
          
          # Try to extract make.log from the failed build
          # Build without push to get the container locally
          docker buildx build context --file Dockerfile \
            --platform linux/amd64 \
            --build-arg BASE_IMAGE=quay.io/jupyter/minimal-notebook:latest \
            --build-arg ACL2_COMMIT=${{ steps.acl2-commit.outputs.commit }} \
            --build-arg ACL2_CERTIFY_OPTS="-j 6" \
            --build-arg ACL2_CERTIFY_TARGETS=basic \
            --load \
            -t acl2-build-test 2>&1 || true
          
          # Try to copy make.log from the container if it exists
          CONTAINER_ID=$(docker create acl2-build-test 2>/dev/null || echo "")
          if [ -n "$CONTAINER_ID" ]; then
            docker cp $CONTAINER_ID:/home/acl2/make.log ./build-logs/make.log 2>/dev/null || \
              echo "Could not extract make.log - file may not exist" > ./build-logs/extraction-failed.txt
            docker rm $CONTAINER_ID
          else
            echo "Could not create container from failed build" > ./build-logs/extraction-failed.txt
          fi

      - name: Upload build logs
        if: steps.docker-build.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: acl2-build-logs
          path: ./build-logs/
          if-no-files-found: ignore

      - name: Check build result
        run: |
          if [[ "${{ steps.docker-build.outcome }}" == "failure" ]]; then
            echo "Docker build failed!"
            exit 1
          fi

      - name: Generate build summary
        run: |
          echo "## Docker Image Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image Tags:**" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.docker-meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**ACL2 Commit:** ${{ steps.acl2-commit.outputs.commit }}" >> $GITHUB_STEP_SUMMARY
          echo "**Platforms:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Pull command:**" >> $GITHUB_STEP_SUMMARY
          echo '```bash' >> $GITHUB_STEP_SUMMARY
          echo "docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
